FROM amazonlinux:latest

RUN yum update
RUN yum install gcc -y
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
ADD src /webapp/src
ADD Cargo.toml /webapp/Cargo.toml
WORKDIR "/webapp"
RUN source $HOME/.bashrc && cargo build --release --bin webapp

ENTRYPOINT ["/webapp/target/release/webapp"]
